export const PROJECT_DOMAINS = [
  'BFSI – Banking, Financial Services & Insurance',
  'Healthcare & Life Sciences',
  'Pharmaceuticals',
  'Retail & E-commerce',
  'Telecommunications',
  'Media & Entertainment',
  'Travel & Hospitality',
  'Transportation & Logistics',
  'Automotive',
  'Manufacturing',
  'Energy & Utilities',
  'Oil & Gas',
  'Government & Public Sector',
  'Education & EdTech',
  'Real Estate & PropTech',
  'Construction & Engineering',
  'Agriculture & AgriTech',
  'Food & Beverage',
  'Insurance / InsurTech',
  'FinTech',
  'LegalTech',
  'HRTech',
  'MarTech',
  'AdTech',
  'Cybersecurity',
  'IT Infrastructure & Managed Services',
  'Cloud Computing',
  'SaaS / Enterprise Software',
  'AI / Machine Learning',
  'Data & Analytics',
  'Blockchain / Web3',
  'IoT / Connected Devices',
  'Gaming',
  'Semiconductor & Electronics',
  'Aerospace & Defense',
  'Supply Chain & Procurement',
  'CRM / Customer Experience',
  'ERP / Enterprise Applications',
  'DevOps / Platform Engineering',
  'Digital Transformation',
] as const;

export type ProjectDomain = (typeof PROJECT_DOMAINS)[number];
